routes/web.php
<?php

use App\Http\Controllers\Backend\BannerController;
use App\Http\Controllers\Backend\Brand\BrandController;
use App\Http\Controllers\Backend\Category\CategoryController;
use App\Http\Controllers\Backend\LoginController;
use App\Http\Controllers\Backend\Product\ProductController;
use App\Http\Controllers\Backend\User\UserController;
use App\Http\Controllers\Frontend\Index\IndexController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/









// Frontend routes start

route::get('/',[IndexController::class,'home'])->name('home');





// Frontend routes end





// Backend routes





// Route::get('/index',[TestController::class,'index'])->name('test');

Route::prefix('admin')->group(function () {


    Route::get('/', [LoginController::class, 'dashboard'])->name('dashboard')->middleware('auth');

    Route::get('/login', [LoginController::class, 'login'])->name('login');

    Route::post('/dologin', [LoginController::class, 'dologin'])->name('dologin');
    Route::get('/logout', [LoginController::class, 'logout'])->name('logout');



    //admin and Employee both can access this group
    Route::group(['middleware' => 'admin.employee'], function () {

        //banner section
        Route::resource('/banner', BannerController::class);
        Route::post('banner_status', [BannerController::class, 'bannerStatus'])->name('banner.status');


        //category section
        Route::resource('/category', CategoryController::class);
        Route::post('category_status', [CategoryController::class, 'categoryStatus'])->name('category.status');
        Route::post('category/{id}/child', [CategoryController::class, 'getChildByParentID']);
    });



    //only Admin can access this group
    Route::group(['middleware' => 'admin'], function () {

        //user add section
        Route::resource('/user', UserController::class);
        Route::post('user_status', [UserController::class, 'userStatus'])->name('user.status');
    });

    //authenticated users can access
    Route::middleware(['auth'])->group(function () {


        //User profile update section
        Route::get('/profile', [UserController::class, 'userprofile'])->name('profile');
        Route::patch('/profile/picture', [UserController::class, 'profilepicture'])->name('profilepicture');
        Route::patch('/profile/password', [UserController::class, 'changepassword'])->name('changepassword');
        Route::patch('/profile/basicinfo', [UserController::class, 'basicinfo'])->name('basicinfo');



        //Brand section
        Route::resource('/brand', BrandController::class);
        Route::post('brand_status', [BrandController::class, 'brandStatus'])->name('brand.status');

        //product section
        Route::resource('/product', ProductController::class);
        Route::post('product_status', [ProductController::class, 'productStatus'])->name('product.status');
    });
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    protected $fillable=[
        'title',
        'slug',
        'summary',
        'description',
        'stock',
        'cat_id',
        'photo',
        'price',
        'offer_price',
        'discount',
        'size',
        'conditions',
        'vendor_id',
        'status',
        'brand_id',
        'cat_id',
        'child_cat_id',
        'vendor_id',
    ];
}

app/Http/Controllers/Backend/Product/ProductController.php
<?php

namespace App\Http\Controllers\Backend\Product;

use App\Models\Product;
use App\Models\Categorie;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::orderBy('id', 'DESC')->paginate(4);
        //dd($allBanners);
        return view('Backend.Layouts.Product.index', compact('products'));
    }

    public function productStatus(Request $request)
    {
        //dd($request->all());
        if ($request->mode == 'true') {

            DB::table('products')->where('id', $request->id)->update(['status' => 'active']);
        } else {
            DB::table('products')->where('id', $request->id)->update(['status' => 'inactive']);
        }
        return response()->json(['msg' => 'Status updated successfully', 'status' => 'true']);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Backend.Layouts.Product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd($request->all());
        $request->validate([
            'title'         =>  'string|required',
            'summary'       =>  'string|required',
            'description'   =>  'string|required',
            'stock'         =>  'numeric',
            'price'         =>  'numeric',
            'discount'      =>  'nullable|numeric',
            'conditions'    =>  'nullable',
            'photo'         =>  'required',
            'status'        =>  'required',
            'cat_id'        =>  'required|exists:categories,id',
            'child_cat_id'  =>  'nullable|exists:categories,id',
            'size'          =>  'nullable',
            'status'        =>  'nullable|in:active,inactive',
        ]);
        $data = $request->all();


        $slug = Str::slug($request->input('title'));
        $slug_count = Product::where('slug', $slug)->count();
        if ($slug_count > 0) {
            $slug = time() . '-' . $slug;
        }
        $data['slug'] = $slug;

        $data['offer_price'] = ($request->price - (($request->price * $request->discount) / 100)); // 150-((150*10)/100) suppose here, price is 150 , discount is 10, divided by 100 is equal to stored in  offer price 
        //dd($data);

        $status = Product::create($data);
        if ($status) {
            return redirect()->route('product.index')->with('success', 'Product successfully created');
        } else {
            return back()->with('error', 'Something went wrong!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);
        if ($product) {

            return view('Backend.Layouts.Product.edit', compact('product'));
        } else {
            return back()->with('error', 'Product not found');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = Product::find($id);
        if ($product) {
            $this->validate($request, [
                'title'         =>  'string|required',
                'summary'       =>  'string|required',
                'description'   =>  'string|required',
                'stock'         =>  'numeric',
                'price'         =>  'numeric',
                'discount'      =>  'nullable|numeric',
                'conditions'    =>  'nullable',
                'photo'         =>  'required',
                'status'        =>  'required',
                'cat_id'        =>  'required|exists:categories,id',
                'child_cat_id'  =>  'nullable|exists:categories,id',
                'size'          =>  'nullable',
                'status'        =>  'nullable|in:active,inactive',
            ]);

            $data = $request->all();

            $data['offer_price'] = ($request->price - (($request->price * $request->discount) / 100)); // 150-((150*10)/100) suppose here, price is 150 , discount is 10, divided by 100 is equal to stored in  offer price 
            //dd($data);
            $status = $product->fill($data)->save();
            if ($status) {
                return redirect()->route('product.index')->with('success', 'Product successfully updated');
            } else {
                return back()->with('error', 'Something went wrong!');
            }
        } else {
            return back()->with('error', 'Product not found');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::find($id); //find each data by their id
        if ($product) {
            $status = $product->delete();
            if ($status) {
                return redirect()->route('product.index')->with('success', 'product deleted successfully');
            } else {
                return redirect()->back()->with('error', 'Something went wrong!');
            }
        } else {
            return back()->with('error', 'Data not found');
        }
    }
}

resources/views/Backend/Layouts/Product/index.blade.php
@extends('Backend.backEndMaster')
@section('main_content')
    <div class="card">
        {{-- @dd($products); --}}


        <div class="header">
            <h2>All Product</h2>
            <br>
            <a href="{{ route('product.create') }}" class="btn btn-sm btn-outline-primary"><i class="icon-plus">Create new
                    Product</i> </a>
            <h2>
                <p class="float-right ">Tottal Products : {{ $tottal_products }} </p>
            </h2>
        </div>

        @if (session('success'))
            <div class="alert alert-success alert-dismissible fade show" id="alert" role="alert">
                {{ session('success') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @elseif ($errors->any())
            @foreach ($errors->all() as $error)
                <div class="alert alert-danger alert-dismissible fade show" id="alert" role="alert">
                    {{ $error }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endforeach
        @endif
        <div class="body">
            <div class="table-responsive">
                <table id="table_id" class="table table-hover m-b-0 c_list">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Title</th>
                            <th>Photo</th>
                            <th>Price</th>
                            <th>Discount</th>
                            <th>Size</th>
                            <th>Condition</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($products as $item)
                        @php
                            $photo=explode(',',$item->photo);
                        @endphp
                            <tr>
                                <td>
                                    {{ $loop->iteration }}
                                </td>
                                <td>

                                    <p class="c_name">{{ $item->title }} </p>
                                </td>

                                <td>
                                    <img src="{{ $photo[0] }}" alt="Product photo"
                                        style=";max-height: 100px; max-width: 100px">
                                </td> 
                                <td>
                                    ${{ number_format($item->price, 2) }}
                                </td>

                                <td>
                                    {{ $item->discount, 2 }}%
                                </td>
                                <td>{{ $item->size }}</td>

                                <td>
                                    @if ($item->conditions == 'new')
                                        <span class="badge badge-success">{{ $item->conditions }}</span>
                                    @elseif ($item->conditions == 'popular')
                                        <span class="badge badge-primary">{{ $item->conditions }}</span>
                                    @else
                                        <span class="badge badge-warning">{{ $item->conditions }}</span>
                                    @endif
                                </td>
                                <td>
                                    <input type="checkbox" name="toogle" value="{{ $item->id }}"
                                        data-toggle="switchbutton" {{ $item->status == 'active' ? 'checked' : '' }}
                                        data-onlabel="active" data-offlabel="inactive" data-size="sm" data-onstyle="success"
                                        data-offstyle="danger">
                                </td>
                                <td>
                                    <a href="{{ route('product.show', $item->id) }}" data-toggle="modal"
                                        data-target="#productID{{ $item->id }}" data-toggle="tooltip"
                                        class=" float-left ml-2 btn btn-sm btn-outline-primary" title="view"><i
                                            class="fa fa-eye"></i></a>


                                    <a href="{{ route('product.edit', $item->id) }}" data-toggle="tooltip"
                                        class=" float-right ml-2 btn btn-sm btn-outline-warning" title="edit"><i
                                            class="fa fa-edit"></i></a>


                                    <form class="float-left ml-2 " action="{{ route('product.destroy', $item->id) }}"
                                        method="post">
                                        @csrf
                                        @method('delete')
                                        <a href="" data-toggle="tooltip" class="dltBtn btn btn-sm btn-outline-danger"
                                            title="delete" data-id="{{ $item->id }}"><i class="fa fa-trash"></i></a>
                                    </form>
                                </td>





                                <!-- Modal -->
                                <div class="modal fade" id="productID{{ $item->id }}" tabindex="-1" role="dialog"
                                    aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                    <div class="modal-dialog modal-dialog-centered" role="document">


                                        @php
                                            $product = \App\Models\Product::where('id', $item->id)->first();
                                        @endphp


                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLongTitle">
                                                    {{ Str::upper($product->title) }}
                                                </h5>

                                                <div class="col align-self-end"
                                                    style="  padding-right: initial;text-align: right;">
                                                    <strong>Status:</strong>
                                                    @if ($product->status == 'inactive')
                                                        <p class="badge badge-danger">{{ $product->status }}</p>
                                                    @else
                                                        <p class="badge badge-success">{{ $product->status }}</p>
                                                    @endif

                                                </div>

                                            </div>
                                            <div class="modal-body">
                                                <strong>Summary:</strong>
                                                <p>{!! html_entity_decode($product->summary) !!}</p>

                                                <strong>Description:</strong>
                                                <p>{!! html_entity_decode($product->description) !!}</p>

                                                <div class="row">
                                                    <div class="col-md-4 ">
                                                        <strong>Price:</strong>
                                                        <p class="badge badge-primary">
                                                            ${{ number_format($product->price, 2) }}</p>
                                                    </div>
                                                    <div class="col-md-4">
                                                        <strong>Discount:</strong>
                                                        <p class="badge badge-danger">{{ $product->discount }}%</p>
                                                    </div>

                                                    <div class="col-md-4">
                                                        <strong>Offer Price:</strong>
                                                        <p class="badge badge-success">
                                                            ${{ number_format($product->offer_price, 2) }}</p>
                                                    </div>
                                                    <div class="col-md-4">
                                                        <strong>Brand:</strong>
                                                        <p class="badge badge-primary">
                                                            {{ \App\Models\Brand::where('id', $product->brand_id)->value('title') }}
                                                        </p>
                                                    </div>
                                                    <div class="col-md-4">
                                                        <strong>Stock:</strong>
                                                        <p class="badge badge-primary">
                                                            {{ $product->stock }}
                                                        </p>
                                                    </div>
                                                    <div class="col-md-4">
                                                        <strong>Size:</strong>
                                                        <p class="badge badge-success">{{ $product->size }}</p>
                                                    </div>
                                                </div>

                                                <div class="row">
                                                    <div class="col-md-4">
                                                        <strong>Category:</strong>
                                                        <p class="badge badge-warning">
                                                            {{ \App\Models\Categorie::where('id', $product->cat_id)->value('title') }}
                                                        </p>
                                                    </div>
                                                    <div class="col-md-4">
                                                        <strong>Child Category:</strong>
                                                        <p class="badge badge-warning">
                                                            {{ \App\Models\Categorie::where('id', $product->child_cat_id)->value('title') }}
                                                        </p>
                                                    </div>
                                                    <div class="col-md-4">
                                                        <strong>Condition:</strong>
                                                        <p class="badge badge-primary">{{ $product->conditions }}</p>
                                                    </div>

                                                    <div class="col-md-4">
                                                        <strong>Vendor:</strong>
                                                        <p class="badge badge-success">
                                                            {{ \App\Models\User::where('id', $product->vendor_id)->value('full_name') }}
                                                        </p>
                                                    </div>

                                                </div>


                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary"
                                                    data-dismiss="modal">Close</button>
                                                <button type="button" class="btn btn-primary">Save changes</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {{-- modal end --}}
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {{ $products->links() }}
            </div>
        </div>
    </div>
@endsection